### DISCUSSION TITLE
Receiving 404 Error from jupyter_app_launcher

### DISCUSSION THREAD

**Discussion by PeerBoerner1** [trungleduc/jupyter_app_launcher#57] [Q&A]
I've installed jupyter_app_launcher on AWS SageMaker JupyterLab 4.0.12 and enabled the extension.  I can see the extension in the enabled extensions section of jupyter lab.  I've followed the directions and created the config file in one of the listed directories shown by `jupyer --paths under the data section, specifically: /home/sagemaker-user/.local/share/jupyter/jupyter_app_launcher/config.yaml`

The contents of the config.yaml file is what you provide as an example:
```
- title: URL example
  description: Example of opening a URL in a tab
  source: https://jupyterlab.readthedocs.io/en/stable/
  type: url
  catalog: Documentation
  args:
      sandbox: [ 'allow-same-origin', 'allow-scripts', 'allow-downloads', 'allow-modals', 'allow-popups']
```
For some reason, I get the following error in the logs and not sure how to resolve the issue:

`[W 2024-02-17 18:06:40.709 ServerApp] 404 POST /jupyterlab/default/jupyterlab-app-launcher?1708193200288 (5963036dacbe4b96b20ca61a7a8672e9@169.255.255.1) 34.20ms referer=https://vgykdx9cyn9pju1.studio.us-east-1.sagemaker.aws/jupyterlab/default/lab?`

Any guidance would be greatly appreciated.

Many thanks in advance.
