### ISSUE TITLE
Add a `jupyterlab-commands` launcher type

### ISSUE THREAD

**Issue by bollwyvl** [trungleduc/jupyter_app_launcher#19]
## Elevator Pitch

Having a launcher type that ran a list of commands would be useful for a number of general cases.

## Motivation

This would harmonize with other systems like [jupyterlab_commands](https://github.com/timkpaine/jupyterlab_commands), and possibly replace (or become the implementation for) a few of the existing items.

## Design Ideas

Update the schema to allow things like:
```yaml
- type: jupyterlab-commands
  commands: 
   - label: Open Notebook
     id: filebrowser:open:
     args: 
       path: SomeNotebook.ipynb
   - label: Run all cells
     id: runmenu:restart-and-run-all
   - label: Save
     id: docmanager:save
   - label: Export
     id: notebook:export-to-format
     args: 
       format: html
   - label: Open HTML
     id: filebrowser:open:
     args:
       path: SomeNotebook.html
```

On the implementation side, it should just be able to `await execute(id, args)` each in turn. If one failed, it could report what stage failed.

Commands that return interesting values might be a bit hard, but could potentially be named and reused.
