### ISSUE TITLE
No items are displayed in the launcher

### ISSUE THREAD

**Issue by fieeman** [trungleduc/jupyter_app_launcher#24]
Hello!

this is my first issue on github, if I'm making any mistake, let me know :)

I installed using pip

and using the *jupyter labextension list* command I can see that it is enabled
```
JupyterLab v3.5.3
/opt/tljh/user/share/jupyter/labextensions
        jupyter_app_launcher v0.1.5 enabled OK (python, jupyter_app_launcher)
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v3.1.1 enabled OK (python, jupyterlab_widgets)
        @jupyterlab/server-proxy v3.2.2 enabled OK
        @jupyter-server/resource-usage v0.6.4 enabled OK (python, jupyter-resource-usage)
```
*jupyter serverextension list*
```
config dir: /opt/tljh/user/etc/jupyter
    jupyter_server_proxy  enabled
    - Validating...
      jupyter_server_proxy  OK
    jupyter_app_launcher  enabled
    - Validating...
      jupyter_app_launcher 0.1.5 OK
    jupyter_nbextensions_configurator  enabled
    - Validating...
      jupyter_nbextensions_configurator 0.6.1 OK
    jupyter_resource_usage  enabled
    - Validating...
      jupyter_resource_usage 0.6.4 OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.5.3 OK
    nbgitpuller  enabled
    - Validating...
      nbgitpuller 1.1.1 OK
    nteract_on_jupyter  enabled
    - Validating...
      nteract_on_jupyter 2.1.3 OK

```

using the *jupyter --path* command, I can see the following

```
config:
    /root/.jupyter
    /root/.local/etc/jupyter
    /opt/tljh/user/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /root/.local/share/jupyter
    /opt/tljh/user/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /root/.local/share/jupyter/runtime
```

I have created the folder *jupyter_app_launcher* in */root/.jupyter* and in */opt/tljh/user/etc/jupyter* and created the config.yaml file with this content

```
- title: URL example
  description: Example of opening a URL in a tab
  source: https://jupyterlab.readthedocs.io/en/stable/
  type: url
  catalog: Other
  args:
      sandbox: [ 'allow-same-origin', 'allow-scripts', 'allow-downloads', 'allow-modals', 'allow-popups']

```
after doing all this and restarting the service, I don't see any new items in the launcher and in the browser console I see this message
```
JupyterLab extension jupyter_app_launcher is activated!
```
so I don't know what's going on, if you could give me some suggestions I would be very grateful.
