### ISSUE TITLE
Add a  launcher type to open a notebook with Voila in a new web page

### ISSUE THREAD

**Issue by huyuhuster** [trungleduc/jupyter_app_launcher#27]
Sometimes people want to show their app in full screen. So if we just render the predefined notebook in dashboard mode, there will be much useless page space.  
       I suggest adding a launcher type to open a notebook with Voila in a new web page.

**Comment by trungleduc** [comment]
You can open a notebook with voila in a new tab with the following config:

```yaml
- title: Voila example (new window)
  description: Example of opening voila in a new browser window
  source: http://127.0.0.1:8888/voila/render/name-of-your-notebook.ipynb
  type: url
  catalog:  Demo
  args:
      createNewWindow: true
```

You might need to adapt the server IP and Port
