### ISSUE TITLE
Add custom support for opening a terminal and running a specified command

### ISSUE THREAD

**Issue by dhirschfeld** [trungleduc/jupyter_app_launcher#56]
The first part is easy with the `jupyterlab-commands` type:
```yaml
  type: jupyterlab-commands
  source:
    - label: Open Terminal
      id: 'terminal:open'
      args:
        name: Browsr
```
...but it appears that there is no way to use that to execute a command (e.g. launch a terminal app) for security reasons:
https://github.com/jupyterlab/jupyterlab/pull/5916

[`initialCommand`](https://github.com/jupyterlab/jupyterlab/blob/49f6ec28b738243a53a947d544bebafafcbd4a73/packages/terminal/src/tokens.ts#L114) is still a constructor arg so `jupyterlab_app_launcher` could define a special `terminal` type and create the terminal and run the initial command via the typescript api.
