### ISSUE TITLE
Icon is missing for `type: url` with a kernel catalog

### ISSUE THREAD

**Issue by Aleksei-Poliakov** [trungleduc/jupyter_app_launcher#87]
Assume you have a config like this:
```
- title: Visual Studio Code [↗]
  description: Open Visual Studio Code in a new tab
  icon: /usr/lib/code-server/lib/vscode/out/media/code-icon.svg
  source: ${JUPYTERHUB_PUBLIC_URL}codeserver/
  type: url
  catalog: Notebook
  args:
    createNewWindow: true
```
It is supposed to add a new menu item to the `Notebook` section with the specified item. But instead of that svg, the icon ends up being the letter `V`. This happens for two reasons:
1. When a command is constructed in `jupyter_app_launcher`, specifically in `index.ts` https://github.com/trungleduc/jupyter_app_launcher/blob/140c47f0afa8aaa9c75e8f2065818d4d29b0b558/src/index.ts#L60 - it force-sets the `icon` property and even more specifically - sets it to be an `LabIcon`
2. When jupyterlab makes a decision what icon to display in https://github.com/jupyterlab/jupyterlab/blob/e55daf1f1f6e89ed6b0d72e316d0e4a92805c146/packages/launcher/src/widget.tsx#L300 - it bases the decision on `kernel` variable (which is effectively boils down to https://github.com/jupyterlab/jupyterlab/blob/e55daf1f1f6e89ed6b0d72e316d0e4a92805c146/packages/launcher/src/widget.tsx#L165 - "is the category Notebook or Console") - and if it's a kernel notebook, the icon that `jupyter_app_launcher` is ignored - instead it expects to see the icon to be in `kernelIconUrl` - and it can't be an svg, or rather than being `LabIcon` it's supposed to be just a href to the file

**Comment by trungleduc** [comment]
Hi, it's only an issue with the `Notebook` catalog, right?

**Comment by Aleksei-Poliakov** [comment]
I hit it on the `Notebook` catalog, but I expect exactly the same issue if you use `Console` catalog as it's in the list of catalogs that are "supposed to have a kernel".

**Comment by trungleduc** [comment]
So it's more a JupyterLab issue? Do you have any suggestion to fix it in jupyter-app-launcher?

**Comment by Aleksei-Poliakov** [comment]
One way would be to add a new field called `kernelIconUrlHref`, e.g.
```
- title: Visual Studio Code [↗]
  description: Open Visual Studio Code in a new tab
  kernelIconUrlHref: /codeserver/icon.png
  source: ${JUPYTERHUB_PUBLIC_URL}codeserver/
  type: url
  catalog: Notebook
  args:
    createNewWindow: true
```
Instead of reading the content of the file like with an `icon`, `jupyter-app-launcher` will just take that value from yaml through python all the way to TypeScript where it goes directly into the `kernelIconUrl` property of the object in `launcher.add`:
```
    launcher.add({
      command: config.id,
      category: config.catalog ?? 'Jupyter App',
      rank: idx,
      kernelIconUrl: config.kernelIconUrlHref
    });
```

There is probably a more elegant solution where there is a single property `icon` in the configuration and then depending on what is it (e.g. a pointer to a file on a disk, inlined data like `data:image/svg+xml;base64,Cjxzdmcg...` or a href string) it's treated differently and is ultimately slotted either into the `launcher.add` or into `commands.addCommand`
