### ISSUE TITLE
Examples not working under JupyterLab 4.0

### ISSUE THREAD

**Issue by rickmcgeer** [trungleduc/jupyter_app_launcher#92]
I'm using jupyter_app_launcher with JupyterLab 4.0.  I've created the file  /opt/conda/etc/jupyter/jupyter_app_launcher/jp_app_launcher.yaml and the file
/opt/conda/etc/jupyter/jp_app_launcher.yaml.  Thet are identical and shown here:
```
- title: URL example
  description: Example of opening a URL in a tab
  source: https://jupyterlab.readthedocs.io/en/stable/
  type: url
  catalog: Another catalog
  args:
      sandbox: [ 'allow-same-origin', 'allow-scripts', 'allow-downloads', 'allow-modals', 'allow-popups']

- title: Terminal example
  description: Example of opening JupyterLab terminal
  type: terminal
  source: 'ls -l'
  cwd: '../'
  args:
    reuse: true
  catalog: Config 2
```

jupyter --path is:
```
config:
    /home/vscode/.jupyter
    /home/vscode/.local/etc/jupyter
    /opt/conda/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/vscode/.local/share/jupyter
    /opt/conda/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/vscode/.local/share/jupyter/runtime
```
Nonetheless, the icons aren't showing.  See the screenshot.

The extension successfully loaded:
```
[I 2025-04-12 23:43:37.437 ServerApp] jupyter_app_launcher | extension was successfully loaded.
[I 2025-04-12 23:43:37.470 ServerApp] jupyter_lsp | extension was successfully loaded.
```
I'm running JupyterLab 4.0.0,, jupyter_app_launcher      0.3.2
What am I doing wrong?

![Image](https://github.com/user-attachments/assets/5934a893-033b-4064-9290-cf25f01c213a)
